### PR TITLE
Fix installation in Windows

### PR DESCRIPTION
**Pull request by davidegorbani**
In the `CMakeLists.txt` I added an if statement to check if the operating system that is installing the project is Windows and if it is the flag `BUILD_SHARED_LIBS` is set to OFF.

CC @dariosortino

### CODE REVIEW

**Comment by traversaro** [comment]
It would be great if in the long term we fixed `BUILD_SHARED_LIBS=ON` on Windows. In theory it should be sufficient to have https://github.com/ami-iit/biomechanical-analysis-framework/blob/7c4a70845d2ccad68de673d60a485f42352e4f8b/CMakeLists.txt#L49-L52, but probably something is not working as expected. Can we at least open an issue in which you copy&paste the problem with `BUILD_SHARED_LIBS=ON`?

**Review by traversaro — APPROVED** [review]

**Review by Gianlucamilani — APPROVED** [review]

**Comment by davidegorbani** [comment]
> Can we at least open an issue in which you copy&paste the problem with `BUILD_SHARED_LIBS=ON`?

Yes, we opened #37.

**Comment by davidegorbani** [comment]
I rebased the branch and now the Windows CI is failing due to the `ResolveRoboticsURICpp` library.

**Comment by davidegorbani** [comment]
I would close this PR and not merge it since we found a solution to install the examples on Windows (see https://github.com/ami-iit/biomechanical-analysis-framework/issues/37#issuecomment-2188190300).

**Pull request closed without merging**
