### PR TITLE
Add logging feature

### PR DESCRIPTION
**Pull request by RiccardoGrieco**
As per title, this PR adds the text logging utility to the BAF library. In addition, it also adds CI build workflows.

The feature relies on the `[bipedal-locomotion-framework](https://github.com/ami-iit/bipedal-locomotion-framework)`'s one, just changing the name/prefix of the logged message to `baf` instead of `blf`.

More specifically, the feature relies on the following PR of `blf` which is merged but not yet released: https://github.com/ami-iit/bipedal-locomotion-framework/pull/582.
For this reason the tag used is the commit `c1cb3fa3329cae7515de6d453bc099dde2cd0645` and the CI, which mostly relies on conda-based dependencies, installs `blf` from source. 
Related TODOs will be removed once after the next version of `blf` is released.

### CODE REVIEW

**Comment by RiccardoGrieco** [comment]
Somehow I managed to find the cause of the failure on `windows` https://github.com/ami-iit/biomechanical-analysis-framework/actions/runs/4042357636/jobs/6949962545#step:11:78.

Turns out that Windows paths have a restriction of `260` chars (see [here](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry)).

Now, the file that is being attempted to generate in the step above mentioned is: `D:/a/biomechanical-analysis-framework/biomechanical-analysis-framework/bipedal-locomotion-framework/build/src/YarpUtilities/CMakeFiles/yarp_idl_to_dir/thrifts/BipedalLocomotion/YarpUtilities/vectorscollection//BipedalLocomotion/YarpUtilities/VectorsCollection.cpp`, which has **`263`** chars.

In https://github.com/ami-iit/biomechanical-analysis-framework/pull/10/commits/6c943a7a886a83c50a26e178f995363725b0d15a I shortened the name of the directory where `bipedal-locomotion-framework` is cloned to `blf` to fix this issue.

**Comment by RiccardoGrieco** [comment]
Finally all checks are passing!

**Review by lrapetti — APPROVED** [review]
The logger and initial skeleton are there, for me we can merge.

I don't know if it makes any sense to add a line in the `CHANGELOG` such that at the first release of the library, we have a list of features.

**Comment by RiccardoGrieco** [comment]
> The logger and initial skeleton are there, for me we can merge.
> 
> I don't know if it makes any sense to add a line in the `CHANGELOG` such that at the first release of the library, we have a list of features.

Done @lrapetti. Thanks for the review, merging.

**Comment by DanielePucci** [comment]
Super cool, first PR with implementation elements, well done!

**Pull request merged**
